Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -87,9 +87,13 @@ jobs:
        # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
     - name: Deploy to Firebase Hosting
       run: |
-        cd projekt
-        npm install -g firebase-tools
-        firebase deploy --only hosting
+        if [ -d "projekt/build/web" ]; then
+          npm install -g firebase-tools
+          firebase deploy --only hosting
+        else
+          echo "Directory 'build/web' does not exist, aborting deploy"
+          exit 1
+        fi
       env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
       working-directory: projekt
