Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -87,31 +87,29 @@ jobs:
         name: build-web
         path: projekt/build/web
 
+    - name: check firebase.json existance
+      run: |
+        ls
+      working-directory: projekt
 
-    - name: Deploy to Firebase Hosting
-      uses: w9jds/firebase-action@master
-      with:
-        args: deploy --only hosting
-        path: projekt
-      env:
-        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+
     
 
     
 
   
-    #- name: Deploy to Firebase Hosting
-     # run: |
-      #  if [ -d "build/web" ]; then
-       #   npm install -g firebase-tools
-        #  firebase deploy --only hosting
-        #else
-         # echo "Directory 'build/web' does not exist, aborting deploy"
-         # exit 1
-        #fi
-      #env:
-       # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
-      #working-directory: projekt
+    - name: Deploy to Firebase Hosting
+      run: |
+        if [ -d "build/web" ]; then
+          npm install -g firebase-tools
+          firebase deploy --only hosting
+        else
+          echo "Directory 'build/web' does not exist, aborting deploy"
+          exit 1
+        fi
+      env:
+        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+      working-directory: projekt
 
        
 
